version: '3.0'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - network
        ports:
            - "8080:80"
        environment:
            DATABASE_URL: postgres://docker:docker@db:5432/bibles
            RUST_BACKTRACE: 1
        volumes:
            - .:/usr/src/app
            - registry:/root/.cargo/registry

volumes:
    registry:
        driver: local

networks:
    network:
